<?php
session_start();
unset($_SESSION['user_id']);
unset($_SESSION['first_name']);
unset($_SESSION['last_name']);
unset($_SESSION['key']);
unset($_SESSION['post_code']);
unset($_SEESION['delivery_address']);
unset($_SESSION['user_prefix']);
unset($_SESSION['user_fname']);
unset($_SESSION['user_lname']);
unset($_SESSION['user_mobile']);
unset($_SESSION['user_telephone']);
unset($_SESSION['user_fax']);
unset($_SESSION['delivery_email']);
unset($_SESSION['user_city']);
unset($_SESSION['primary_address']);
unset($_SESSION['secondary_address']);
unset($_SESSION['user_county']);
unset($_SESSION['country']);
unset($_SESSION['delivery_date']);
unset($_SESSION['user_card_msg']);
unset($_SESSION['user_notes']);
unset($_SESSION['c_code']);
header("location:login.php");
?>
